import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import TodoContextProvider from "@/context/TodoContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TodoContextProvider>
        <Provider>
          <body>
            <main className="app">
              <Navbar />
              {children}
            </main>
          </body>
        </Provider>
      </TodoContextProvider>
    </html>
  );
}
